### PR TITLE
fix(sheet2code-ui): fix `renderPage` bugs

### PR DESCRIPTION
**Pull request by YuCJ**
- `1b80f48`:  react-dom (renderer) and webpack bundled react should share the same version or it will encounter an error
- `1cb2071`: fix missing quotation marks for js string. replace `if` condition with `try ... catch` for better debugging when encountering client side error
- `4ec805c`: fix action type typo

### CODE REVIEW

**Comment by nickhsine** [comment]
> * `1b80f48`:  react-dom (renderer) and webpack bundled react should share the same version or it will encounter an error

What kind of errors will occur?

**Comment by YuCJ** [comment]
> > * `1b80f48`:  react-dom (renderer) and webpack bundled react should share the same version or it will encounter an error
> 
> What kind of errors will occur?
> How could I reproduce errors?

1. at @twreporter/sheet2code-ui use react@16.13.1, react-dom@16.13.1 to build the webpack bundle
2. at cloud function, use react-dom at version different from 16.13.1 with `renderPage`

then will invoke error with 'more than one copy of React in the same app': https://reactjs.org/docs/error-decoder.html/?invariant=321

**Comment by nickhsine** [comment]
### Error Message
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

The root cause is that `cloud-functions` install two versions(16.13.1 and ^16.3.0) of `react`.
`react@16.13.1` specified in `cloud-functions`'s `package.json`
`react@^16.3.0`  specified in `sheet2code-ui`'s `package.json`
In the version of react with hooks, it does not allow multiple react installations in server side.

### Solution
in `cloud-functions`, run `yarn-deduplicate` to deduplicate react.
Thus, we can revert this commit https://github.com/twreporter/orangutan-monorepo/pull/10/commits/1b80f4837a56d0698127fab7b9f6a6357c30f553 .

**Comment by nickhsine** [comment]
LGTM 💯

**Comment by YuCJ** [comment]
updated according to review

**Comment by YuCJ** [comment]
> updated according to review

forgot to update package.json of sheet2code..

**Comment by nickhsine** [comment]
LGTM !

**Pull request merged**
